### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by darkvergus** [satoru8/BDv2#3]
**Describe the bug**
Info is out of place when hovering over any of the items

**To Reproduce**
1. Go to discord
2. Click on server errors
3. hover over any of the items
4. info out of place

**Expected behavior**

**Screenshots**

![](https://cdn.discordapp.com/attachments/477443723085479956/563822330015383553/unknown.png)

**Desktop (please complete the following information):**
 - FullScreenServerSettings/
 - latest

**Comment by satoru8** [comment]
Fixed for v1
